# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-01-04 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devson', '0002_auto_20151217_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estiloobjeto',
            old_name='V_TipoLetra',
            new_name='V_Estilo',
        ),
        migrations.RenameField(
            model_name='estiloobjeto',
            old_name='V_Color',
            new_name='V_Valor',
        ),
        migrations.RemoveField(
            model_name='estiloobjeto',
            name='K_Objeto',
        ),
        migrations.AddField(
            model_name='estiloobjeto',
            name='K_Proyecto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='devson.Proyecto'),
        ),
    ]
