# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-01-05 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devson', '0003_auto_20160103_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='objeto',
            name='V_IdLocal',
            field=models.CharField(default='nodo', max_length=9),
            preserve_default=False,
        ),
    ]
