# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-01-05 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devson', '0004_objeto_v_idlocal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objeto',
            name='K_TipoObjeto',
            field=models.CharField(max_length=10),
        ),
    ]
