# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-01-06 00:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devson', '0006_auto_20160105_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objeto',
            name='K_HijoDe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devson.Objeto'),
        ),
    ]
