# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-01-09 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devson', '0007_auto_20160105_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objeto',
            name='K_TipoObjeto',
            field=models.CharField(max_length=200),
        ),
    ]
